name: secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Server Connection Key
        run: echo "Server Connection Key is ${{ secrets.Server_Connection_Key }}"
